RedHatInsights/insights-results-aggregator-utils

input/2report.py, input/anonymize.py, input/fill_in_results.sh, input/gen_broken_messages.py, input/produce.sh, input/random_payload_generator.py, input/stat.py, setup.cfg
Scripts to work with input messages.
=> Input messages handlers

reports/stat.py
=> Fixed issue #3

input/2report.py
=> Fix issues in 2report found by pylinter

run_pycodestyle.py
Script to run pycodestyle from Python
=> Script to run pycodestyle from Python

ci/issue.py
=> Script to report issue on GH

run_pycodestyle.py
Fix issue #28: added missing docstring
=> Fix issue #28: added missing docstring

ci/issue.py
Fix issue #30 - rephrassing docstring
=> Fix issue #30 - rephrassing docstring

input/2report.py
Fix issue #32 - D103: Missing docstring in public function
=> Fix issue #32 - D103: Missing docstring in public function

README.md, checks/json_check.py
=> JSON checker to accept directory

anim/anim_aggregator_consumer.go
=> Fix issue #47

anim/anim_aggregator_consumer.go
=> Fixed issue #46

anim/anim_aggregator_consumer.go
=> Fixed issue #45

README.md, logs/anonymize_aggegator_log.py
=> Aggregator logs anonymizer

README.md, logs/anonymize_ccx_pipeline_log.py
=> Ccx data pipeline anonymizer

README.md, logs/anonymize_ccx_pipeline_log.py
Fix example in anonymize ccx pipeline log
=> Fix example in anonymize ccx pipeline log

monitoring/go_metrics.py
Documentation for `go_metrics.py` script
=> Documentation for go_metrics.py script

anim/anim_aggregator_consumer.go, anim/anim_smart_proxy.go
=> Documentation for anim files

docs/2report.html, docs/affected_clusters.html, docs/anim_aggregator_consumer.html, docs/anim_smart_proxy.html, docs/anonymize.html, docs/anonymize_aggregator_log.html, docs/anonymize_ccx_pipeline_log.html, docs/gen_broken_jsons.html, docs/gen_broken_messages.html, docs/go_metrics.html, docs/issue.html, docs/json_check.html, docs/pycco.css, docs/random_payload_generator.html, docs/run_pycodestyle.html, docs/stat.html, docs/upload_timestamps.html
=> Doc in literate programming

README.md, checks/open_api_check.py, docs/packages/open_api_check.html
=> OpenAPI checker

reports/affected_clusters.py
Updated script to check affected clusters
=> Updated script to check affected clusters

README.md, reports/reports.py
Script to generate elementary reports
=> Script to generate elementary reports

docs/packages/reports.html
Generated documentation for `reports.py` script.
=> Generated documentation for reports.py script

README.md
Provide description and usage subsections for  utility
=> Provide description and usage subsections for  utility

README.md
Provide description and usage subsections for `2report.py` utility
=> Provide description and usage subsections for 2report.py utility

README.md
=> Fixed issue #122

README.md
Provide description and usage subsections for stat.py script
Fixes issue #123
=> Provide description and usage subsections for stat.py script

README.md
Added Usage section in description of package 'affected_clusters.py'
Fixes issue #132
=> Added Usage section in description of package 'affected_clusters.py'

README.md
Added link to generated documentation for script reports.py
=> Added link to generated documentation for script reports.py

README.md
Updated documentation for upload_timestamps.py script
=> Updated documentation for upload_timestamps.py script

README.md
=> Description of random_payload_generator.py

README.md
Added description for run_pycodestyle.py script
Fixes #136
=> Added description for run_pycodestyle.py script

README.md
=> Add description about script anim_aggregator_consumer into README.md

README.md
Add description about script `anim_smart_proxy.html` into README.md
Fixes issue #99
=> Add description about script anim_smart_proxy.go into README.md

docs/packages/reports.html
Updated generated documentation for report.py
=> Updated generated documentation for report.py

converters/json2edn.py
=> Script to convert data to EDN format from JSON format

README.md, docs/index.md, docs/packages/insights_operator_prometheus.html
=> Documentation for insights operator prometheus tool

README.md, docs/index.md, docs/packages/insights_operator_to_web_console.html
=> Documentation for insights operator to web console tool

README.md, anim/anim.go, docs/index.md, docs/packages/anim.html
=> Description for anim package

README.md, anim/anim_aggregator_consumer.go, docs/packages/anim_aggregator_consumer.html
=> Description for anim aggregator consumer.go

README.md, anim/anim_smart_proxy.go, docs/packages/anim_smart_proxy.html
=> Description for `anim_smart_proxy.go`

README.md, anim/insights_operator_pull_only.go, docs/packages/insights_operator_pull_only.html
Utility to create animation of io pulling
See #160
=> Utility to create animation of io pulling

README.md, anim/insights_operator_prometheus.go, docs/packages/insights_operator_prometheus.html
=> Provide description for insights operator prometheus.go

anim/insights_operator_to_web_console.go, docs/packages/insights_operator_to_web_console.html
=> Provide description for insights operator to web console.go

anim/insights_operator_pull_only.go, docs/index.md, docs/packages/insights_operator_pull_only.html
Description for insights operator pull only
=> Description for insights operator pull only

docs/index.md, docs/packages/run_pycodestyle.html, run_pycodestyle.py
Updated comments in `run_pycodestyle.py` script
=> Updated comments in run pycodestyle script

checks/json_check.py, docs/packages/json_check.html
Usage section in `json_check.py`
=> Usage section in `json_check.py`

checks/open_api_check.py, docs/packages/open_api_check.html
Updated comments in `open_api_check.py`
=> Updated comments in `open_api_check.py`

CODEOWNERS
=> List of codeowners

checks/open_api_check.py, docs/packages/open_api_check.html
Add link to generated documentation for source file `checks/open_api_check.py`
Fixes: #183
=> Add link to generated documentation for source file `checks/open_api_check.py`

checks/json_check.py, docs/packages/json_check.html
Add link to generated documentation for source file `checks/json_check.py`
=> Add link to generated documentation for source file `checks/json_check.py`

docs/packages/run_pycodestyle.html, run_pycodestyle.py
Add link to generated documentation for source file `run_pycodestyle.py`
Fixes #181
=> Add link to generated documentation for source file `run_pycodestyle.py`

docs/packages/random_payload_generator.html, input/random_payload_generator.py
Add link to generated documentation for source file `input/random_payload_generator.py`
Fix issue #180
=> Add link to generated documentation for source file `input/random_payload_generator.py`

docs/packages/anonymize_ccx_pipeline_log.html, logs/anonymize_ccx_pipeline_log.py
Add link to generated documentation for source file `logs/anonymize_ccx_pipeline_log.py`
Fixes #179
=> Add link to generated documentation for source file `logs/anonymize_ccx_pipeline_log.py`

docs/packages/anonymize_aggregator_log.html, logs/anonymize_aggregator_log.py
Add link to generated documentation for source file `logs/anonymize_aggregator_log.py`
Fixes #178
=> Add link to generated documentation for source file `logs/anonymize_aggregator_log.py`

docs/packages/anonymize.html, input/anonymize.py
Add link to generated documentation for source file `input/anonymize.py`
Fixes #175
=> Add link to generated documentation for source file `input/anonymize.py`

docs/packages/2report.html, input/2report.py
Add link to generated documentation for source file `input/2report.py`
Fixes #174
=> Add link to generated documentation for source file `input/2report.py`

docs/packages/gen_broken_messages.html, input/gen_broken_messages.py
Add link to generated documentation for source file `input/gen_broken_messages.py`
Fixes #177
=> Add link to generated documentation for source file `input/gen_broken_messages.py`

docs/packages/affected_clusters.html, reports/affected_clusters.py
Add link to generated documentation for source file `reports/affected_clusters.py`
Fix issue #203
=> Add link to generated documentation for source file `reports/affected_clusters.py`

docs/packages/go_metrics.html, monitoring/go_metrics.py
Add link to generated documentation for source file `monitoring/go_metrics.py`
Fixes #202
=> Add link to generated documentation for source file `monitoring/go_metrics.py`

docs/packages/gen_cert_key.html, kubernetes/gen_cert_key.py
Add link to generated documentation for source file `kubernetes/gen_cert_key.py`
Fixes #201
=> Add link to generated documentation for source file `kubernetes/gen_cert_key.py`

converters/json2edn.py, docs/packages/json2edn.html
Add link to generated documentation for source file `converters/json2edn.py`
Fixes #200
=> Add link to generated documentation for source file `converters/json2edn.py`

anim/insights_operator_to_web_console.go, docs/packages/insights_operator_to_web_console.html
Add link to generated documentation for source file `anim/insights_operator_to_web_console.go`
Fix issue #199
=> Add link to generated documentation for source file `anim/insights_operator_to_web_console.go`

anim/insights_operator_pull_only.go, docs/packages/insights_operator_pull_only.html
Add link to generated documentation for source file `anim/insights_operator_pull_only.go`
Fix issue #198
=> Add link to generated documentation for source file `anim/insights_operator_pull_only.go`

anim/insights_operator_prometheus.go, docs/packages/insights_operator_prometheus.html
Add link to generated documentation for source file `anim/insights_operator_prometheus.go`
Fixes #197
=> Add link to generated documentation for source file `anim/insights_operator_prometheus.go`

anim/anim_smart_proxy.go, docs/packages/anim_smart_proxy.html
Add link to generated documentation for source file `anim/anim_smart_proxy.go`
Fixes #196
=> Add link to generated documentation for source file `anim/anim_smart_proxy.go`

anim/anim.go, docs/packages/anim.html
Add link to generated documentation for source file `anim/anim.go`
Fixes #195
=> Add link to generated documentation for source file `anim/anim.go`

anim/anim_aggregator_consumer.go, docs/packages/anim_aggregator_consumer.html
Add link to generated documentation for source file `anim/anim_aggregator_consumer.go`
Fixes #194
=> Add link to generated documentation for source file `anim/anim_aggregator_consumer.go`

docs/packages/anonymize_ccx_pipeline_log.html, logs/anonymize_ccx_pipeline_log.py
=> Fix issue #223

docs/packages/anonymize_aggregator_log.html, logs/anonymize_aggregator_log.py
=> Fix issue #224

docs/packages/stat.html, reports/cluster_id_distribution.py, reports/stat.py
=> Fix issue #225

docs/packages/reports.html, reports/reports.py
=> Fix issue #226

docs/packages/organizations.html
=> Fixed issue #227

docs/packages/cluster_results_age.html, reports/cluster_results_age.py
=> Fix issue #228

docs/packages/affected_clusters.html, reports/affected_clusters.py
=> Fix issue #229

checks/json_check.py, docs/packages/json_check.html
=> Fix issue #230

checks/open_api_check.py, docs/packages/open_api_check.html
=> Fix issue #231

docs/packages/go_metrics.html, monitoring/go_metrics.py
=> Fix issue #232 - proper URL to generated documentation

docs/packages/run_pycodestyle.html, run_pycodestyle.py
Fix issue #233 - added URL to generated documentation
=> Fix issue #233 - added URL to generated documentation

ci/issue.py, docs/packages/issue.html
Fix issue #234 - added link to generated documentation
=> Fix issue #234 - added link to generated documentation

converters/json2edn.py, docs/packages/json2edn.html
Fix issue #236 - added missing URL to generated documentation
=> Fix issue #236 - added missing URL to generated documentation

docs/packages/gen_cert_key.html, kubernetes/gen_cert_key.py
Fix issue #237 - link to generated documentation
=> Fix issue #237 - link to generated documentation

docs/packages/upload_timestamps.html, s3/upload_timestamps.py
Fix issue #238 - added missing URL to generated documentation
=> Fix issue #238 - added missing URL to generated documentation

docs/packages/anonymize.html, input/anonymize.py
Fix issue #239 - updated link to generated documentation
=> Fix issue #239 - updated link to generated documentation

docs/packages/gen_broken_messages.html, input/gen_broken_messages.py
Fix issue #240 - missing URL do generated documentation
=> Fix issue #240 - missing URL do generated documentation

docs/packages/random_payload_generator.html, input/random_payload_generator.py
Fix issue #241 - link to generated documentation
=> Fix issue #241 - link to generated documentation

docs/packages/gen_broken_jsons.html, input/gen_broken_jsons.py
Fix issue #242 - link to generated doc
=> Fix issue #242 - link to generated doc

docs/packages/2report.html, input/2report.py
Fix issue #243 - missing doc link
=> Fix issue #243 - missing doc link

docs/packages/cluster_id_distribution.html, reports/cluster_id_distribution.py
Fix issue #264 - create generated documentation
=> Fix issue #264 - create generated documentation

README.md, anim/anim_external_data_pipeline.go, docs/index.md, docs/packages/anim_external_data_pipeline.html
=> Update aggregator consumer animator

README.md, converters/edn2json.py, docs/index.md, docs/packages/edn2json.html
=> Tool to convert EDN to JSON

README.md, docs/manifest.txt
Package manifest
Fixes #288
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Package manifest

README.md, docs/packages/st.html, stage_tester/st.py
Script to retrieve results from the pipeline (running on Stage usually)
Can be checked easily against stage.
=> Script to retrieve results from the pipeline (running on Stage usually)

README.md, docs/packages/st.html, stage_tester/st.py
Remove "account number" from everywhere not to confuse people.
N/A
=> Remove "account number" from everywhere

.travis.yml, database/cleanup_old_results.py, reports/affected_clusters.py, reports/reports.py, stage_tester/st.py
Travis CI setup
- CI setup
- 
Let's try the CI
=> Travis CI setup

README.md, docs/packages/st.html, stage_tester/st.py
Result comparator phase #1
An example of generated output:
Can be run locally against two sets of results taken from real pipeline.
=> Result comparator phase #1

README.md, stage_tester/st.py
Additional info in the table
N/A
=> Additional info in the table

README.md, stage_tester/st.py
Slightly better documentation for `st` tool
N/A
=> Slightly better documentation for `st` tool

stage_tester/st.py
Export recommendations table
An example of new report:
Can be done locally against two result sets.
=> Export recommendations table

docs/packages/st.html
=> Pycco-generated doc file

README.md, stage_tester/st.py
Export processing times to CSV
Can be checked locally.
=> Export processing times to CSV

README.md, docs/packages/st.html, stage_tester/st.py
=> Docs for `st` tool

README.md, docs/packages/pta.html, stage_tester/pta.py
Script to retrieve and analyze processing times from reports taken from external data pipeline
(MVP to be demonstrated tomorrow)
Can be run locally.
=> `pta` tool

README.md, stage_tester/pta.py
Bin size specification on CLI
Can be checked locally
=> Bin size specification

docs/packages/pta.html
=> Updated PTA generated doc

stage_tester/st_xlsx.py
MVP: Stage tester with XLSX export
Fixes # [(issue)](https://issues.redhat.com/browse/CCXDEV-6461)
Anybody can check it locally.
=> MVP: Stage tester with XLSX export

stage_tester/st_xlsx.py
Styled spreadsheet output
An example of generated workbook:
Can be checked locally
=> Styled spreadsheet output

stage_tester/ui_actions.py
Tool for interacting with CCX services in stage environment and simulate OCM UI rule-related actions. The actions supported, for a given rule, are: like, dislike, enable, disable, disable with feedback.
Tested directly against the services running in stage
=> Simulate OCM UI actions over recommendations

stage_tester/ui_actions.py
Format accepted operations
N/A
=> Format accepted operations

stage_tester/ui_actions.py
=> Minor improvements

README.md, s3/download_prod_data/config.go
Added the description of CCXDEV-6230 feature to description.
Fixes #CCXDEV-6230
=> Add description to documentation about download_prod_data tool

stage_tester/st.py
Refactoring: reading cluster list
N/A
=> Refactoring: reading cluster list

stage_tester/st.py
Ability to read cluster list from CSV
N/A
=> Ability to read cluster list from CSV

stage_tester/st.py
=> Fixed grammar in `st.py`

stage_tester/st_xlsx.py
=> Sync doc in `st_xlsx.py`

stage_tester/st_xlsx.py
=> Refactoring st_xlsx.py

stage_tester/pta.py
=> Reformatted `pta.py`

stage_tester/ui_actions.py
Reformatted `ui_actions.py`
N/A
=> Reformatted `ui_actions.py`

stage_tester/st.py
=> Reformatted `st.py`

stage_tester/st_xlsx.py
=> Reformatted `st_xlsx.py`

README.md, docs/index.md, docs/packages/gen_messages.html, input/gen_messages.py
Script to generate messages
Fixes #335 
Done on CI
=> Script to generate messages

input/gen_messages.py
Fix: numeric type required
Can be tested locally.
=> Fix: numeric type required

docs/packages/affected_clusters.html, docs/packages/plot_write_duration.html, docs/packages/plot_write_speed_1.html, docs/packages/plot_write_speed_2.html, docs/packages/reports.html
=> Added pycco doc

s3/download_prod_data/writer.go
=> Use octal literal

checks/json_check.py, checks/open_api_check.py, ci/issue.py, database/cleanup_old_results.py, input/gen_broken_jsons.py, input/gen_broken_messages.py, input/random_payload_generator.py, kubernetes/gen_cert_key.py, run_pycodestyle.py, s3/upload_timestamps.py
Python code reformat by Black
Done on CI
=> Python code reformat by Black

s3/download_prod_data/main.go, s3/download_prod_data/s3.go
Performance improvement: large S3 configuration structure passed by pointer
Done on CI
=> Performance improvement: large S3 configuration structure passed by pointer

monitoring/go_metrics.py, monitoring/kafka_lags.py
Python code reformat #3
Done on CI
=> Python code reformat #3

logs/anonymize_aggregator_log.py, logs/anonymize_ccx_pipeline_log.py, stage_tester/st.py, stage_tester/st_xlsx.py, stage_tester/ui_actions.py
Python code reformat #4
Done on CI
=> Python code reformat #4

monitoring/processing_time.py
=> Processing time script

converters/json2edn.py
=> Fixed wrong help

on_demand_data_gathering/go.mod, on_demand_data_gathering/go.sum, on_demand_data_gathering/publisher.go
Publisher, the stub for PoC
- Stub for On Demand Data Gathering publisher
N/A
=> Publisher, the stub

on_demand_data_gathering/publisher.go
=> Finished publisher

run_pycodestyle.py
(trivial) Add type to run pycodestyle
N/A
=> (trivial) Add type to run pycodestyle

pyproject.toml
- Pyproject settings
- Allow us to enable Ruff on CI later
- Configuration update
N/A right now
=> Pyproject settings

.travis.yml
Updated Python versions on CI
- Configuration update
To be visible on CI/Travis
=> Updated Python versions on CI

checks/open_api_check.py, database/cleanup_old_results.py, input/gen_broken_jsons.py, input/gen_messages.py, reports/plot_write_speed_1.py, reports/plot_write_speed_3.py, s3/upload_timestamps.py
- Fix unused imports in Python sources
Fixes partially CCXDEV-11905
N/A
=> Fix unused imports in Python sources

stage_tester/st.py, stage_tester/st_xlsx.py
=> Fixed unnecessary calls

checks/json_check.py, checks/open_api_check.py, database/cleanup_old_results.py, input/2report.py, input/gen_broken_jsons.py, input/gen_broken_messages.py, input/gen_messages.py, kubernetes/gen_cert_key.py, logs/anonymize_aggregator_log.py, logs/anonymize_ccx_pipeline_log.py, monitoring/go_metrics.py, monitoring/kafka_lags.py, reports/affected_clusters.py, reports/reports.py, stage_tester/pta.py, stage_tester/st_xlsx.py
Fixed issues found by Ruff: start of multi line docstrings
N/A
=> Fixed issues found by Ruff: start of multi line docstrings

checks/json_check.py, exporter/ploter.py, input/gen_broken_jsons.py, input/gen_broken_messages.py, input/gen_messages.py, input/random_payload_generator.py, reports/plot_time_duration_3.py, stage_tester/pta.py, stage_tester/st.py, stage_tester/ui_actions.py
- Docstring fixes
- Removed unused imports
- Removed unused variables
- Make Ruff a bit more happy :)
N/A at this moment
=> Docstring fixes, removed unused imports, removed unused variables

converters/edn2json.py, converters/json2edn.py, database/cleanup_old_results.py, reports/affected_clusters.py, reports/plot_time_duration_3.py, reports/plot_write_duration.py, reports/plot_write_speed_1.py, reports/plot_write_speed_2.py, reports/plot_write_speed_3.py, reports/reports.py, setup.py, stage_tester/__init__.py, stage_tester/st.py, stage_tester/ui_actions.py
Fixed docstrings in all scripts
N/A
=> Fixed docstrings in all scripts

.github/workflows/ruff.yml
Setup Ruff on CI
- Configuration update
Let's see that :robot: on CI.
=> Setup Ruff on CI
